/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.is2.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto.is2.controller.Admin;

/**
 *
 * @author carlosguardiola
 */
public class VentanaPrincipalAdmin extends javax.swing.JFrame {

    private final Admin admin;

    /**
     * Creates new form VentanaPrincipalJugador
     */
    public VentanaPrincipalAdmin(JFrame VentanaAnterior, Admin admin) {
        this.admin = admin;
        this.ventanaAnterior = VentanaAnterior;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonReservar = new javax.swing.JButton();
        botonPartidos = new javax.swing.JButton();
        botonResponsable = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonAdministrar = new javax.swing.JButton();
        botonAddGerente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonMorosos = new javax.swing.JButton();
        botonAdministrarJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal Jugador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonReservar.setText("Rservar Sede");
        botonReservar.setPreferredSize(new java.awt.Dimension(122, 32));
        botonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservarActionPerformed(evt);
            }
        });

        botonPartidos.setText("Datos Partidos");
        botonPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPartidosActionPerformed(evt);
            }
        });

        botonResponsable.setText("Responsable");
        botonResponsable.setPreferredSize(new java.awt.Dimension(122, 32));
        botonResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResponsableActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonAdministrar.setText("Administrar Clubs");
        botonAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarActionPerformed(evt);
            }
        });

        botonAddGerente.setText("AddGerente");
        botonAddGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddGerenteActionPerformed(evt);
            }
        });

        jButton2.setText("AddEntrenador");

        botonMorosos.setText("Morosos");
        botonMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMorososActionPerformed(evt);
            }
        });

        botonAdministrarJugador.setText("Admin Jugador");
        botonAdministrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonMorosos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(botonAddGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReservar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAdministrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAdministrarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPartidos)
                    .addComponent(botonAdministrar))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAddGerente)
                    .addComponent(jButton2))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMorosos)
                    .addComponent(botonAdministrarJugador))
                .addGap(72, 72, 72)
                .addComponent(botonSalir)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.setVisible(false);
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResponsableActionPerformed
        VentanaResponsable responsable = new VentanaResponsable(this);
        responsable.setVisible(true);
    }//GEN-LAST:event_botonResponsableActionPerformed

    private void botonPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPartidosActionPerformed
        VentanaPartido partido = new VentanaPartido(this);
        partido.setVisible(true);
    }//GEN-LAST:event_botonPartidosActionPerformed

    private void botonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActionPerformed
        VentanaReserva reserva = new VentanaReserva(this);
        reserva.setVisible(true);
    }//GEN-LAST:event_botonReservarActionPerformed

    private void botonAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministrarActionPerformed
        VentanaClub clubs = new VentanaClub(this, admin);
        clubs.setVisible(true);
    }//GEN-LAST:event_botonAdministrarActionPerformed

    private void botonAddGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddGerenteActionPerformed
        // TODO add your handling code here:
        VentanaAddGerente addGerente = new VentanaAddGerente(this, admin);
        addGerente.setVisible(true);
    }//GEN-LAST:event_botonAddGerenteActionPerformed

    private void botonMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMorososActionPerformed
        // TODO add your handling code here:
        VentanaMorosidad morosos = new VentanaMorosidad(this, admin);
        morosos.setVisible(true);
    }//GEN-LAST:event_botonMorososActionPerformed

    private void botonAdministrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministrarJugadorActionPerformed
        // TODO add your handling code here:
        VentanaAdministrarJugador administrarJugador = new VentanaAdministrarJugador(this, admin);
        administrarJugador.setVisible(true);
    }//GEN-LAST:event_botonAdministrarJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddGerente;
    private javax.swing.JButton botonAdministrar;
    private javax.swing.JButton botonAdministrarJugador;
    private javax.swing.JButton botonMorosos;
    private javax.swing.JButton botonPartidos;
    private javax.swing.JButton botonReservar;
    private javax.swing.JButton botonResponsable;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
    private JFrame ventanaAnterior;
}
