/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.is2.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto.is2.controller.Admin;

/**
 *
 * @author carlosguardiola
 */
public class VentanaNuevoClub extends javax.swing.JFrame {

    private final Admin admin;
    private int creado = 0;

    /**
     * Creates new form VentanaNuevoClub
     */
    public VentanaNuevoClub(JFrame VentanaAnterior, Admin admin) {
        this.ventanaAnterior = VentanaAnterior;
        this.admin = admin;
        initComponents();

        for (int i = 0; i < admin.consultarProvincias().size(); i++) {
            comboProvincias.addItem(admin.consultarProvincias().get(i).toString());
        }

        textSede.setEditable(false);
        textGerente.setEditable(false);
        textEntrenador.setEditable(false);
        botonBuscarGerente.setEnabled(false);
        botonBuscarEntrenador.setEnabled(false);
        botonAnyadir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSede = new javax.swing.JLabel();
        labelGerente = new javax.swing.JLabel();
        labelEntrenador = new javax.swing.JLabel();
        labelProvincia = new javax.swing.JLabel();
        botonAnyadir = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        comboProvincias = new javax.swing.JComboBox<>();
        textSede = new javax.swing.JTextField();
        textGerente = new javax.swing.JTextField();
        textEntrenador = new javax.swing.JTextField();
        botonBuscarGerente = new javax.swing.JButton();
        botonBuscarEntrenador = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir Club");

        labelSede.setText("Sede");

        labelGerente.setText("Gerente");

        labelEntrenador.setText("Entrenador");

        labelProvincia.setText("Provincia");

        botonAnyadir.setText("Añadir");
        botonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnyadirActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonBuscarGerente.setText("Buscar");
        botonBuscarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGerenteActionPerformed(evt);
            }
        });

        botonBuscarEntrenador.setText("Buscar");

        labelNombre.setText("Nombre");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProvincia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSede)
                            .addComponent(labelGerente)
                            .addComponent(labelEntrenador)
                            .addComponent(labelNombre)
                            .addComponent(botonVolver))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textSede, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textGerente)
                                    .addComponent(textEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonAnyadir, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(botonBuscarGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonBuscarEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProvincia)
                    .addComponent(comboProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSede)
                    .addComponent(textSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGerente)
                            .addComponent(textGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEntrenador)
                            .addComponent(textEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscarGerente)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarEntrenador)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnyadir)
                    .addComponent(botonVolver))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        String nombre = textNombre.getText();
        String comprobar;
        comprobar = nombre.replaceAll(" ", "");
        if (comprobar.length() == 0) {
            JOptionPane.showMessageDialog(this, "Introduce el nombre del club", "error añadir club", JOptionPane.ERROR_MESSAGE);
        } else {
            admin.anyadirClub(comboProvincias.getSelectedItem().toString(), nombre);
            botonCrear.setEnabled(false);
            textSede.setEditable(true);
            botonBuscarGerente.setEnabled(true);
            botonAnyadir.setEnabled(true);
            creado = 1;
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonBuscarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarGerenteActionPerformed
        // TODO add your handling code here:
        VentanaModificarClub modificargerente = new VentanaModificarClub(this, admin, textNombre.getText(), comboProvincias.getSelectedItem().toString());
        this.setVisible(false);
        modificargerente.setVisible(true);
    }//GEN-LAST:event_botonBuscarGerenteActionPerformed

    private void botonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnyadirActionPerformed
        // TODO add your handling code here:
        String sede = textSede.getText();
        String provincia = comboProvincias.getSelectedItem().toString();
        String comprobar;
        int error = 0;
        comprobar = sede.replaceAll(" ", "");
        if (comprobar.length() == 0) {
            JOptionPane.showMessageDialog(this, "Introduce una sede para el club", "error añadir club", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < admin.consultarClub(provincia).size(); i++) {
                if (admin.consultarClub(provincia).get(i).toString().equals(textNombre.getText())) {
                    admin.consultarClub(provincia).get(i).ModificarSede(sede);
                    if (admin.consultarClub(provincia).get(i).getGerente() == null) {
                        error = 1;
                    }
                }
            }

            if (error == 1) {
                JOptionPane.showMessageDialog(this, "Introduce un gerente para el club", "error añadir club", JOptionPane.ERROR_MESSAGE);
            } else {
                this.setVisible(false);
            }

        }
    }//GEN-LAST:event_botonAnyadirActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        if (creado == 0) {
            this.setVisible(false);
            ventanaAnterior.setVisible(true);
        } else {
            admin.eliminarClub(textNombre.getText(), comboProvincias.getSelectedItem().toString());
            this.setVisible(false);
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnyadir;
    private javax.swing.JButton botonBuscarEntrenador;
    private javax.swing.JButton botonBuscarGerente;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> comboProvincias;
    private javax.swing.JLabel labelEntrenador;
    private javax.swing.JLabel labelGerente;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelProvincia;
    private javax.swing.JLabel labelSede;
    private javax.swing.JTextField textEntrenador;
    private javax.swing.JTextField textGerente;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textSede;
    // End of variables declaration//GEN-END:variables
    private JFrame ventanaAnterior;
}
